// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application";

import AutocompleteController from "./autocomplete_controller";
application.register("autocomplete", AutocompleteController);

import BulkActionController from "./bulk_action_controller";
application.register("bulk-action", BulkActionController);

import ButtonSelectController from "./button_select_controller";
application.register("button-select", ButtonSelectController);

import DatalistController from "./datalist_controller";
application.register("datalist", DatalistController);

import FormController from "./form_controller";
application.register("form", FormController);

import FormValidationController from "./form_validation_controller";
application.register("form-validation", FormValidationController);

import PaginationController from "./pagination_controller";
application.register("pagination", PaginationController);

import SwitchViewController from "./switch_view_controller";
application.register("switch-view", SwitchViewController);

import ToastController from "./toast_controller";
application.register("toast", ToastController);

import TrixController from "./trix_controller";
application.register("trix", TrixController);

import UploadsController from "./uploads_controller";
application.register("uploads", UploadsController);

import SortingController from "./sorting_controller";
application.register("sorting", SortingController);
